name: Build Folia

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        repository: 'papermc/folia'
        ref: 'main'
        token: ${{ secrets.PAT }} # Replace PAT with your personal access token

    - name: Set up JDK 17
      uses: actions/setup-java@1.0.0
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Find Build Artifacts
      id: find_artifacts
      run: echo ::set-output name=artifact_path::$(find . -type f -name '*.jar')

    - name: Upload build artifacts
      uses: actions/upload-artifact@3.0.0
      with:
        name: folia-build
        path: ${{ steps.find_artifacts.outputs.artifact_path }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Folia Build ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/action-upload-release-asset@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_artifacts.outputs.artifact_path }}
        asset_name: ${{ steps.find_artifacts.outputs.artifact_path }}
        asset_content_type: application/java-archive
